### ISSUE TITLE
Cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by ssm2017** [zach-capalbo/hubs-client-bot#7]
hello
when trying to run : 
```docker run --rm -ti -v /`pwd`:/src buildkite/puppeteer node //src/examples/eggbot.js https://hubs.mozilla.com/6UV6dpG/cautious-slight-gathering```
or
```node examples/eggbot.js https://hubs.mozilla.com/6UV6dpG/cautious-slight-gathering```
i have the error : 
```
>>  A-Frame Version: https://github.com/MozillaReality/aframe
>>  three Version: https://github.com/MozillaReality/three.js
>>  WebVR Polyfill Version: ^0.10.10
>>  %ccore:schema:warn %cDefault value `null` does not match type `string` in component `media-loader`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `null` does not match type `string` in component `media-loader`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `null` does not match type `string` in component `media-loader`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `undefined` does not match type `string` in component `media-image`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `null` does not match type `string` in component `camera-focus-button`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `null` does not match type `string` in component `emit-scene-event-on-remove`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `[object Object]` does not match type `string` in component `media-frame`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `[object Object]` does not match type `string` in component `media-frame`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `[object Object]` does not match type `string` in component `pen`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `[object Object]` does not match type `string` in component `pen-laser`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `[object Object]` does not match type `string` in component `pen-laser`%c  color: orange color: inherit color: orange
>>  %ccore:schema:warn %cDefault value `[object Object]` does not match type `string` in component `pen-laser`%c  color: orange color: inherit color: orange
>>  App version: 1.0.0.20210210231433
>>  Tracking: Sentry DSN: https://013d6a364fed43cdb0539a61d520597a@sentry.prod.mozaws.net/370
>>  Tracking: Google Analytics ID: UA-77033033-12
>>  Using WebGL 2.0 context.
>>  %ccore:schema:warn %cUnknown property `multiview` for component/system `undefined`.%c  color: orange color: inherit color: orange
>>  Using Non-VR bindings.
>>  The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
>>  Insufficient MAX_UNIFORM_BLOCK_SIZE, Disabling batching.
>>  Hub ID: 6UV6dpG
>>  Reticulum @ boring-elf.reticulum.io: v1.0.20210115213815 on earth
>>  Phoenix Socket URL: wss://boring-elf.reticulum.io:443
>>  THREE.GLTFLoader: Duplicating UVs to support aoMap.
>>  Janus host: agitated-elf.reticulum.io:443
>>  Scene URL: https://uploads-prod.reticulum.io/files/002172c6-41f9-4c3e-adc5-f4dd3141b527.bin
>>  THREE.GLTFLoader: Duplicating UVs to support aoMap.
>>  [three-pathfinding]: Use THREE.BufferGeometry, not THREE.Geometry, to create zone.
>>  traverseMeshesAndAddShapes
>>  heightfield or trimesh found on scene
>>  console.groupEnd
Clicking for a button matching /entry__action/
Failed to run. Check botError.png if it exists. Error: Error: Evaluation failed: TypeError: Cannot read property 'click' of undefined
    at __puppeteer_evaluation_script__:5:19
    at ExecutionContext._evaluateInternal (/home/ssm2017/hublot-hubs/hubs-client-bot/node_modules/puppeteer/lib/ExecutionContext.js:93:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async ExecutionContext.evaluate (/home/ssm2017/hublot-hubs/hubs-client-bot/node_modules/puppeteer/lib/ExecutionContext.js:32:16)
    at async PageUtils.clickSelectorClassRegex (/home/ssm2017/hublot-hubs/hubs-client-bot/src/hubs-bot.js:14:5)
    at async HubsBot.enterRoom (/home/ssm2017/hublot-hubs/hubs-client-bot/src/hubs-bot.js:145:5)
    at async run (/home/ssm2017/hublot-hubs/hubs-client-bot/examples/eggbot.js:5:3)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/ssm2017/hublot-hubs/hubs-client-bot/node_modules/puppeteer/lib/helper.js:82:19)
    at DOMWorld.evaluate (/home/ssm2017/hublot-hubs/hubs-client-bot/node_modules/puppeteer/lib/DOMWorld.js:88:24)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
  -- ASYNC --
    at Frame.<anonymous> (/home/ssm2017/hublot-hubs/hubs-client-bot/node_modules/puppeteer/lib/helper.js:82:19)
    at Page.evaluate (/home/ssm2017/hublot-hubs/hubs-client-bot/node_modules/puppeteer/lib/Page.js:548:47)
    at Page.<anonymous> (/home/ssm2017/hublot-hubs/hubs-client-bot/node_modules/puppeteer/lib/helper.js:83:27)
    at PageUtils.clickSelectorClassRegex (/home/ssm2017/hublot-hubs/hubs-client-bot/src/hubs-bot.js:14:21)
    at HubsBot.enterRoom (/home/ssm2017/hublot-hubs/hubs-client-bot/src/hubs-bot.js:145:14)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async run (/home/ssm2017/hublot-hubs/hubs-client-bot/examples/eggbot.js:5:3)
```

**Comment by zach-capalbo** [comment]
Hmm... Yeah, this whole library has likely been broken by the recent Hubs UI changes and will likely need to be largely re-written. I'm not sure if / when this work would be done.

**Comment by ssm2017** [comment]
i have just tested using the old UI (default hubs cloud) to confirm and there are no errors

**Comment by zach-capalbo** [comment]
I believe this issue should be resolved now with the latest version of the package, which has been updated to account for the new hubs interface.
